LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ifneq ($(TARGET_PLATFORM_DEVICE_BASE),)
LOCAL_CFLAGS += -DUSES_BOOTDEVICE_PATH
endif

ifneq ($(BOARD_TRUSTZONE_PARTITION_SIZE),)
    LOCAL_CFLAGS += -DBOARD_TRUSTZONE_PARTITION_SIZE=$(BOARD_TRUSTZONE_PARTITION_SIZE)
else
    LOCAL_CFLAGS += -DBOARD_TRUSTZONE_PARTITION_SIZE=500
endif

LOCAL_C_INCLUDES := bootable/recovery
LOCAL_SRC_FILES := recovery_updater.cpp
LOCAL_MODULE := librecovery_updater_oppo
LOCAL_MODULE_TAGS := eng
include $(BUILD_STATIC_LIBRARY)
